- hosts: research_python7
  vars:
    use_epel: true
    custom_repo: true
    deploy_iptables: true
    envir: prod
# vars_files:
#   - ~/RHACCOUNT
  become: yes
  become_method: sudo

  pre_tasks:
    - name: register RHEL7 repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms"
    - name: register RHEL7 RHSCL Repo
      shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
    - name: register RHEL7 DevTools
      shell: "/usr/bin/subscription-manager repos --enable=rhel-7-server-devtools-rpms"
    - name: list RHEL enabled repos
      shell: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}"
  tasks:
    - name: Install X Windows
      yum:
        name: "@X Window System"
        state: present

    - name: Install Development Tools
#     shell:  yum groupinstall "Development Tools" -y
      yum:
        name: "@Development tools"
        state: present 
#   - name: Install JAVA OpenJDK 1.8
#     shell: yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel -y

## GDAL Patch ######################################################
    - name: Get and Build gdal 2.2.1
      become: yes
      become_method: sudo
      shell: wget http://download.osgeo.org/gdal/2.2.1/gdal-2.2.1.tar.gz -O /tmp/gdal-2.2.1.tar.gz
      shell: tar xvf /tmp/gdal-2.2.1.tar.gz -C /opt/gdalRH7
      shell: /opt/gdalRH7/configure --prefix=/usr/local --with-sfcgal=no
      shell: make -j4
      shell: make install
# unpack, configure, make, make install


    - name: Install python gdal bindings - Pip install gdal 2.2.1
      become: yes
      become_method: sudo
      shell: pip3 install gdal==2.2.1

    - name: create necessary links with ldconfig
      become: yes
      become_method: sudo
      shell: ldconfig

    - name: Ensure epel 7 is installed
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

#- name: Install gdal dependencies
# yum:
#   name: "{{ item }}"
#   state: present
# with_items:
#   - libgdal*dev*
#   - gdal-devel
#   - gdal-libs
#   - proj
#   - proj-devel
#   - proj-nad
#   - proj-epsg



  roles:
#   - epel7
#   - emacsRH7
#   - openjdk1.8
#   - odbc7
#   - postgresql-client
#   - devtools7
#   - python2RH7
#   - python3RH7
#   - pyenvRH7
#   - pycharm7
#   - gocd7
#   - stattransfer14
#   - r_RH7
#   - r-studio-desktopRH7
#   - r-studio-serverRH7
#   - r-studio-server-configRH7
#   - r-shinyRH7
#   - r-shiny-configRH7

# hosts: research_python
# become: yes
# become_method: sudo
# roles:
#   - devtools
#   - devtools6
#   - {role: python, when: "custom_repo"}
#   - {role: python-build, when: "not custom_repo"}
#   - {role: python3, when: "custom_repo"}
#   - {role: python3-build, when: "not custom_repo"}
#   - {role: python-libs}
#   - postgresql-client
#   - r-core
#   - r-libs
#   - r-studio-desktop
#   - r-studio-server
#   - r-studio-server-config
#   - pycharm
#   - gocd
#   - stattransfer14



  post_tasks:
#   - name: register mime types
#     shell: update-mime-database /usr/share/mime/packages/

#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"7
