- hosts: wdcdevrepythonl01
  vars:
    custom_repo: true
# vars_files:
#   - ~/RHACCOUNT
  become: yes
  become_method: sudo

  pre_tasks:
    - name: register RHEL7 repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms"
    - name: register RHEL7 RHSCL Repo
      shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
    - name: register RHEL7 DevTools
      shell: "/usr/bin/subscription-manager repos --enable=rhel-7-server-devtools-rpms"
    - name: list RHEL enabled repos
      shell: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}"
  tasks:
#   - name: Install Development Tools
#     shell:  yum groupinstall "Development Tools" -y

# OpenJDK already installed
#   - name: Install JAVA OpenJDK 1.8
#     shell: yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel -y

## GDAL Patch ######################################################
    - name: Install gdal preliminary addons
      shell: "{{ item }}"
      with_items:
        - wget http://s3.amazonaws.com/etc-data.koordinates.com/gdal-travisci/install-libkml-r864-64bit.tar.gz -O /tmp/install-libkml-r864-64bit.tar.gz
        - mkdir -p /opt/libkml
        - tar xzf /tmp/install-libkml-r864-64bit.tar.gz -C /opt/libkml
        - cp -r /opt/libkml/install-libkml/include/* /usr/local/include
        - cp -r /opt/libkml/install-libkml/lib/* /usr/local/lib
        - ldconfig

    - name: Check if gdal 2.2.3 already deployed
      file:
        stat: /opt/gdal223/gdal-2.2.3
      register: gdal

    - name: Get and Build gdal 2.2.3
      become: yes
      become_method: sudo
      shell: "{{ item }}"
      with_items:
        - wget http://download.osgeo.org/gdal/2.2.3/gdal-2.2.3.tar.gz -O /tmp/gdal-2.2.3.tar.gz
        - mkdir -p /opt/gdal223
        - tar xvf /tmp/gdal-2.2.3.tar.gz -C /opt/gdal223
#       - /opt/gdal223/gdal-2.2.3/configure --prefix=/usr/local/ --with-libkml --with-sfcgal=no
      when: gdal.stat.exists == false

    - name: Configure gdal 2.2.3
      become: yes
      become_method: sudo
      command: "./configure --prefix=/usr/local/ --with-libkml --with-sfcgal=no"
      args:
        chdir: /opt/gdal223/gdal-2.2.3
      when: gdal.stat.exists == false

    - name: Build and install gdal 2.2.3
      become: yes
      become_method: sudo
      shell: make -j4 && make install
      args:
        chdir: /opt/gdal223/gdal-2.2.3
      when: gdal.stat.exists == false

#       - ./configure --prefix=/usr/local/ --with-libkml --with-sfcgal=no
#       - make -j4
#       - make install
    # unpack, configure, make, make install


    - name: Install python gdal bindings - Pip install gdal 2.2.3
      become: yes
      become_method: sudo
      shell: pip3 install gdal==2.2.3
      when: gdal.stat.exists == false

    - name: create necessary links with ldconfig
      become: yes
      become_method: sudo
      shell: ldconfig
      when: gdal.stat.exists == false

    - name: Ensure epel 7 is installed
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

  roles:
#   - epel7
#   - emacs7
#   - emacsRH7
#   - openjdk1.8
#   - odbc7
#   - postgresql-client
#   - devtools7
#   - python2RH7
#   - python3RH7
#   - pyenvRH7
#   - r_RH7

# hosts: research_python
# become: yes
# become_method: sudo
# roles:
#   - devtools
#   - devtools6
#   - {role: python, when: "custom_repo"}
#   - {role: python-build, when: "not custom_repo"}
#   - {role: python3, when: "custom_repo"}
#   - {role: python3-build, when: "not custom_repo"}
#   - {role: python-libs}
#   - postgresql-client
#   - r-core
#   - r-libs
#   - r-studio-desktop
#   - r-studio-server
#   - r-studio-server-config
#   - pycharm
#   - gocd
#   - stattransfer14



  post_tasks:
#   - name: register mime types
#     shell: update-mime-database /usr/share/mime/packages/

#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"7
