# main.yml - Install Python 3.6 from RedHat Satellite
---
- name: Install Python36 packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python36
    - python36-setuptools
    - python36-devel
    - rh-python36-numpy
    - rh-python36-scipy
    - rh-python36-python-tools
    - rh-python36-python-six

- name: Install pip
  easy_install:
    name: pip
    executable: easy_install-3.6
